-- Reset all tables
TRUNCATE TABLE order_items CASCADE;
TRUNCATE TABLE orders CASCADE;
TRUNCATE TABLE menu_items CASCADE;
TRUNCATE TABLE menu_categories CASCADE;
TRUNCATE TABLE tables CASCADE;
TRUNCATE TABLE restaurants CASCADE;

-- Reset sequences if any
ALTER SEQUENCE IF EXISTS restaurants_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS tables_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS menu_categories_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS menu_items_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS orders_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS order_items_id_seq RESTART WITH 1; 